apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello_world
spec:
  selector:
    matchLabels:
      app: hello_world
  template:
    metadata:
      labels:
        app: hello_world
    spec:
      containers:
      - name: hello_world
        image: nginxdemos/hello
        resources:
          limits:
            memory: "512"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080